# Generated by Django 5.1.1 on 2024-09-14 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        ('sujet', '0002_sujetmodel_title_alter_sujetmodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='sujet',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='post',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sujet_message_id', to='sujet.sujetmodel'),
        ),
    ]
