# Generated by Django 5.1.1 on 2024-09-15 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_messagemodel_sujet_messagemodel_name_and_more'),
        ('sujet', '0002_sujetmodel_title_alter_sujetmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sujet.sujetmodel'),
        ),
    ]
