# Generated by Django 5.1.1 on 2024-09-16 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_messagemodel_subject'),
        ('sujet', '0004_remove_sujetmodel_title_sujetmodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='post',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sujet.sujetmodel'),
            preserve_default=False,
        ),
    ]
