# Generated by Django 5.1.1 on 2024-09-15 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forummodel_description_forummodel_title'),
        ('sujet', '0002_sujetmodel_title_alter_sujetmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujetmodel',
            name='forum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forummodel'),
        ),
    ]
