# Generated by Django 5.1.1 on 2024-09-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sujet', '0004_remove_sujetmodel_title_sujetmodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujetmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='sujetmodel',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
