# Generated by Django 5.1.1 on 2024-09-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummodel',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forummodel',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
